# formats
export _BOLD='\e[1m'
export _DIM='\e[2m'
export _UNDERLINE='\e[4m'
export _BLINK='\e[5m'
export _INVERT='\e[7m'
export _HIDE='\e[8m'

# format resets
export _RESET_ALL='\e[0m'
export _RESET_BOLD='\e[21m'
export _RESET_DIM='\e[22m'
export _RESET_UNDERLINE='\e[24m'
export _RESET_BLINK='\e[25m'
export _RESET_INVERT='\e[27m'
export _RESET_HIDE='\e[28m'

# foreground (text) colors
export _DEFAULT='\e[39m'
export _BLACK='\e[30m'
export _RED='\e[31m'
export _GREEN='\e[32m'
export _YELLOW='\e[33m'
export _BLUE='\e[34m'
export _MAGENTA='\e[35m'
export _CYAN='\e[36m'
export _LIGHT_GRAY='\e[37m'
export _DARK_GRAY='\e[90m'
export _LIGHT_RED='\e[91m'
export _LIGHT_GREEN='\e[92m'
export _LIGHT_YELLOW='\e[93m'
export _LIGHT_BLUE='\e[94m'
export _LIGHT_MAGENTA='\e[95m'
export _LIGHT_CYAN='\e[96m'
export _WHITE='\e[97m'

# background colors
export _DEFAULT_BG='\e[49m'
export _BLACK_BG='\e[40m'
export _RED_BG='\e[41m'
export _GREEN_BG='\e[42m'
export _YELLOW_BG='\e[43m'
export _BLUE_BG='\e[44m'
export _MAGENTA_BG='\e[45m'
export _CYAN_BG='\e[46m'
export _LIGHT_GRAY_BG='\e[47m'
export _DARK_GRAY_BG='\e[100m'
export _LIGHT_RED_BG='\e[101m'
export _LIGHT_GREEN_BG='\e[102m'
export _LIGHT_YELLOW_BG='\e[103m'
export _LIGHT_BLUE_BG='\e[104m'
export _LIGHT_MAGENTA_BG='\e[105m'
export _LIGHT_CYAN_BG='\e[106m'
export _WHITE_BG='\e[107m'
